name: Build docker image to Docker Hub only

env:
  DOCKER_IMAGE_NAME: lta-datamall-api
  
on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ "master" ]
jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PSW }}    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./src
        push: true
        tags: tsbsia/${{ env.DOCKER_IMAGE_NAME }}:latest  
    - name: Discord and Telegram notification
      if: failure()
      uses: hunghg255/action-notifications@master
      with:
        discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
        telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
        title: "Build and Publish"
        description: "Failed to build and publish the project {{ EVENT_PAYLOAD.repository.full_name }}."
  notifification:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Notification Success
        uses: hunghg255/action-notifications@master
        if: always()
        with:
           discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
           telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
           telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
           title: "Pushed to Docke Hub"
           description: "Test here: https://labs.play-with-docker.com/"
