# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lta-datamall-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tsbsia.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_093153acc7d9493f8e344b256103f4fc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f62e6e2c14774585a6eb831a6cf6c44d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tsbsia.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_093153acc7d9493f8e344b256103f4fc }}/lta-datamall-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lta-datamall-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1989e47b67f14b95a2b94f5e5d92c0ea }}
        images: 'tsbsia.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_093153acc7d9493f8e344b256103f4fc }}/lta-datamall-api:${{ github.sha }}'